name: Deploy Azure OpenAI Langchain Bot

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["Azure VM Deployment"]
    types:
      - completed

env:
  VM_NAME_VAR: ${{ vars.VM_NAME }}
  LOCATION_VAR: ${{ vars.LOCATION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Ansible
      run: pip install ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i "${VM_NAME_VAR}.${LOCATION_VAR}.cloudapp.azure.com", ansible_playbook.yml -u ${{ secrets.SSH_USER }} --ask-pass --extra-vars "ansible_ssh_pass=${{ secrets.SSH_PASSWORD }} ENV_FILE='${{ secrets.ENV_FILE }}' HOST_URL='http://${VM_NAME_VAR}.${LOCATION_VAR}.cloudapp.azure.com'"
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'

    - name: URL
      run: |
        echo "Admin Portal: http://${VM_NAME_VAR}.${LOCATION_VAR}.cloudapp.azure.com:8080"
        echo "API docs: http://${VM_NAME_VAR}.${LOCATION_VAR}.cloudapp.azure.com:8100/docs"
